name: 'tag-exists-action'
description: 'Checks if a given tag exists'
inputs:
  tag:  
    description: 'Tag to search for'
    required: true
  repo_name:  
    description: 'Specify the name of the GitHub repository in which the GitHub release will be created, edited, and deleted. If the repository is other than the current, it is required to create a personal access token with `repo`, `user`, `admin:repo_hook` scopes to the foreign repository and add it as a secret. Defaults to the current repository'
outputs:
  exists: # id of output
    description: 'true or false'
runs:
  using: 'node16'
  main: 'index.js'
branding:
  icon: 'bookmark'  
  color: 'yellow'
